### PR TITLE
01-BigchainDB-Introduction

### PR DESCRIPTION
**Pull request by michielmulders**

### CODE REVIEW

**Comment by maaxaam** [comment]
Hey there,

After I have read your piece - the following came across my mind:
Is there a project which addresses a similar issue?
Maybe note a few of those if they exist and how they pit one against the other for better understanding of the market and the forces between. 

Cheers,
Max

**Comment by maaxaam** [comment]
@michielmulders @Swader

**Comment by michielmulders** [comment]
@maaxaam Thanks for the review.
I asked the marketing manager of BigchainDB, they could not tell me any competitors.
I'm waiting for an answer from one of the devs to be sure.

In my opinion, there are no similar tools like BigchainDB for storing JSON assets.
It's pretty unique.

**Comment by tyaakow** [comment]
It is an interesting project, although I would like to read more about it's efficiency (financial and performance-wise), comparatively, as @maaxaam said.. Even if just comparison to non-blockchain solutions.

And maybe an ideal use case / cases, who gets to manage the nodes if $100/GB is the price, how centralized is it? (IPFS is just a protocol, not a service, anyone can set up an IPFS node, in comparison).

Maybe it is beyond the scope of the article, but it would add a bit perspective?

@michielmulders @Swader

**Comment by maaxaam** [comment]
you see, there in lies the point. this is a unique solution as it seems. being unique makes a strong selling point. maybe peeps here like @the-codepunker @morrigan can ask a more in depth tech questions about the usability or application of BigchainDB to see if there are any further points of contention. :)

**Comment by the-codepunker** [comment]
@michielmulders @maaxaam 

Hi there. Here's what I fail to see/understand from the text:

1. What are the real world implications of this system (who would benefit from it and how)
2. If there are "people" deciding on validity of the data pushed to this storage system... why wouldn't I just use 2000 nosql or even sql servers on AWS or GCloud ?
3. Maybe I don't get the internals... but creating data ... creates a "string" ? 
4. All the data sent to this chain is public ?
5. Tell us more about how this relates back to MongoDB - I didn't quite get that.

Once I get to understand these from the text... I will even be able to play with some code... and see what goes.

Cheers!

**Comment by tyaakow** [comment]
@the-codepunker  its a layer on top of Mongo

**Comment by michielmulders** [comment]
I've added some better information regarding the link between mongodb/assets/bigchaindb.

IPDB cost is out of scope. I know they are just using amazon and google instances, and some local ones in their office, that's it.

In the end, I found two competitors: noms db (decentralized Git alike db) and orbit-db (serverless, distributed p2P db).

We've planned a practical follow up article to make the use more clear (the example in introduction will be created).

Please let me know.
Thanks for the help thus far!

**Pull request closed without merging**
