### PR TITLE
home mining tutorial - the-codepunker

### PR DESCRIPTION
**Pull request by the-codepunker**
Initial draft of the home-mining tutorial

### CODE REVIEW

**Comment by morrigan** [comment]
Hey, nice machine there :) I've been also playing with mining lately so I'd like to discuss few points.

- Why so high costs for "Metal shelf to assemble the rig on ( ~ EUR 100 ) and  Electrical wiring and assembly by a specialist ( ~ EUR 100)"? Both points are really confusing because for my housing I spent around 20EUR.
- Isn't DDR3 4GB enough? I have 6 GPUs but I am not sure if that really affects.
- Windows might be a no go for bigger number of cards but otherwise it's much easier to setup. I am a Linux user but installing drivers on it is really pain in the a*s sometimes. Also, the link to bitcointalk page 9 is not really informational and straight to the point.
- Claymore miner. I'd like to see that someone really tested all the miners and made the comparison because I got the impression that you can even earn more with a miner taking 1-2% fee than with the one taking 0% fee. I am also confused if you tested it or not because in one sentence you say you didn't and in other one that you tried them all.
- How much does the big fan help? I'd suggest you try smaller coolers (120mm) connected to molex to blow from the wall to the front side. That way all the GPUs could get air flow.

Would love to here more advanced tips, cheers.

**Comment by the-codepunker** [comment]
Hi @morrigan,

- I added a few more pics... that should explain the prices for wiring and setup.
- The asrock h110 pro btc+ works with DDR4... Moreover, because of the amount of ram needed to generate the DAG for 12 GPUs it is much safer to use 8GB instead of 4GB... (i added a screenshot that explains why)
- Using windows is not an option for me because it simply doesn't support more than 8 GPUs of the same kind... it only works with hybrid mining (nvidia + amd)... I added another link to the asrock official website which explains it.
- I modified the text for that and pushed ... at the moment of writing I had only tested claymore on windows, not linux... I have now tested them both and there are no differences in terms of performance between the two.
- The fan thing is a "hack" ... I don't tell anyone to use that... :)

Thanks a lot for the recommendations. I just pushed a new commit with more images, explanations and links.

P.S.
@morrigan, @Swader please tag me when commenting... I disabled notifications unless I'm tagged to avoid being flooded with lots of emails... hope that's OK.

Cheers!

**Comment by maaxaam** [comment]
This seems detailed. I think I would understand more if I had the inclination to build this thing back home. But being in China, ASIC miners can be obtained more easily and for popular currencies would suffice. 

My friend in SA had a lot of challenges even assembling the number of required cards to start up his mining ops, and as you, he was smart enough to get the gaming editions one, so after the sold it due to being to hot and too loud he retained all the value. 

I agree on the point of having a professional set up your electrical network for operation of such size as this is your base of operation. If a breaker jumps out every time someone starts a microwave or a heating appliance that would be silly downtime. 

I like how things were broken down. Even though I am not a native Unix user I have enough content to start asking questions if I would get lost. 

Like the article. 

It is not written for people who easily give up or the faint of heart. But that is the area to reap rewards. 

Max

@the-codepunker @morrigan @Swader

**Comment by the-codepunker** [comment]
@Swader I'm closing this. It's been stale for too long now. Sorry, but it will not be of any use to anyone if it gets published in September.

**Pull request closed without merging**
